#!/bin/sh

#  run.sh
#  BetaOS
#
#  Created by Adam Kopeć on 2/14/16.
#  Copyright © 2016 Adam Kopeć. All rights reserved.

export PATH="$PATH:/Applications/VMware Fusion.app/Contents/Library";

vmrun -T fusion start /Users/adamkopec/Documents/Virtual\ Machines.localized/BetaOS.vmwarevm/BetaOS.vmx;