//
//  unimplemented.m
//  Objective-C Runtime
//
//  Created by Adam Kopeć on 11/28/17.
//

#define UNIMPLEMENTED(x) void x() { ULTDBG(__func__); }

#ifdef ULTDEBUG
#define ULTDBG(x...) printf(x)
#else
#define ULTDBG(x...)
#endif
int _DefaultRuneLocale;

UNIMPLEMENTED(_NSGetEnviron)
UNIMPLEMENTED(getline)
UNIMPLEMENTED(getsectiondata)
UNIMPLEMENTED(__error)
UNIMPLEMENTED(malloc_zone_from_ptr)
UNIMPLEMENTED(snprintf_l)
UNIMPLEMENTED(vdprintf)
UNIMPLEMENTED(fprintf)
UNIMPLEMENTED(dlsym)
UNIMPLEMENTED(dladdr)
UNIMPLEMENTED(close)
UNIMPLEMENTED(read)
UNIMPLEMENTED(posix_memalign)
UNIMPLEMENTED(asl_log)
UNIMPLEMENTED(__swbuf)
UNIMPLEMENTED(_tlv_bootstrap)
UNIMPLEMENTED(malloc_default_zone)
UNIMPLEMENTED(getenv)

/*
 * Math functions
 */

UNIMPLEMENTED(arc4random)
UNIMPLEMENTED(arc4random_uniform)
UNIMPLEMENTED(acosf)
UNIMPLEMENTED(acoshf)
UNIMPLEMENTED(cos)
UNIMPLEMENTED(cosf)
UNIMPLEMENTED(coshf)
UNIMPLEMENTED(cbrtf)
UNIMPLEMENTED(erfcf)
UNIMPLEMENTED(erff)
UNIMPLEMENTED(expm1f)
UNIMPLEMENTED(exp2)
UNIMPLEMENTED(exp2f)
UNIMPLEMENTED(fdimf)
UNIMPLEMENTED(frexp)
UNIMPLEMENTED(frexpf)
UNIMPLEMENTED(fma)
UNIMPLEMENTED(fmaf)
UNIMPLEMENTED(fmal)
UNIMPLEMENTED(nanf)
UNIMPLEMENTED(ilogb)
UNIMPLEMENTED(ilogbf)
UNIMPLEMENTED(ldexp)
UNIMPLEMENTED(ldexpf)
UNIMPLEMENTED(logbf)
UNIMPLEMENTED(log10)
UNIMPLEMENTED(log10f)
UNIMPLEMENTED(log1pf)
UNIMPLEMENTED(log2)
UNIMPLEMENTED(log2f)
UNIMPLEMENTED(hypotf)
UNIMPLEMENTED(nextafterf)
UNIMPLEMENTED(nearbyint)
UNIMPLEMENTED(nearbyintf)
UNIMPLEMENTED(scalbn)
UNIMPLEMENTED(scalbnf)
UNIMPLEMENTED(asinf)
UNIMPLEMENTED(asinhf)
UNIMPLEMENTED(sin)
UNIMPLEMENTED(sinf)
UNIMPLEMENTED(sinhf)
UNIMPLEMENTED(atan2f)
UNIMPLEMENTED(atanf)
UNIMPLEMENTED(atanhf)
UNIMPLEMENTED(tanf)
UNIMPLEMENTED(tanhf)
UNIMPLEMENTED(tgammaf)
UNIMPLEMENTED(lgamma_r)
UNIMPLEMENTED(lgammaf_r)
UNIMPLEMENTED(lgammal_r)
UNIMPLEMENTED(remquo)
UNIMPLEMENTED(remquof)
UNIMPLEMENTED(yn)
UNIMPLEMENTED(jn)

/*
 * Misc
 */

UNIMPLEMENTED(strtod_l)
UNIMPLEMENTED(strtof_l)
UNIMPLEMENTED(strtold_l)
UNIMPLEMENTED(remainder)
UNIMPLEMENTED(remainderf)
UNIMPLEMENTED(remainderl)
UNIMPLEMENTED(__memcpy_chk)
UNIMPLEMENTED(__memmove_chk)
UNIMPLEMENTED(__strlcpy_chk)

UNIMPLEMENTED(sysconf)
UNIMPLEMENTED(trunc)
UNIMPLEMENTED(truncf)
UNIMPLEMENTED(truncl)

UNIMPLEMENTED(fcntl)
UNIMPLEMENTED(ioctl)

UNIMPLEMENTED(open)
UNIMPLEMENTED(openat)
UNIMPLEMENTED(sem_open)

UNIMPLEMENTED(__fpclassifyd)
UNIMPLEMENTED(__fpclassifyf)

#import <stdbool.h>
bool DisableNonpointerIsa = true;
